name: Firebase Deploy

on:
  push:
    branches: [main]  # Change if needed

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (with public registry)
        run: npm install --registry=https://registry.npmjs.org/

      - name: Build project (skip CI warnings)
        run: CI='' npm run build

      - name: Deploy to Firebase Hosting using npx
        run: npx --yes firebase-tools@latest deploy --only hosting --token ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
